version: "3.7"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: chenhung0506/reverse-proxy:${TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
    env_file:
      - dev.env
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf.d:/etc/nginx/conf.d/
      - ./cert/harbor_cert:/etc/cert
      - ./cert/live:/etc/letsencrypt/live
    ports:
      - 80:80
      - 443:443
    environment:
      LB_VIDEOS_URL: 172.17.0.1:80
    restart: always
    #network_mode: "host"
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx
