version: "3.7"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: harbor.chlin.tk/nginx/reverse-proxy:${TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf.d:/etc/nginx/conf.d/
    environment:
      BF_IP: 172.12.0.1
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    # network_mode: "host"
    restart: always
