version: "3.7"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: harbor.chlin.tk/nginx/reverse-proxy:${TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
    env_file:
      - dev.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf.d:/etc/nginx/conf.d/
      - ./cert/harbor_cert:/etc/cert
      - ./cert/live:/etc/letsencrypt/live
    ports:
      - 80:80
      - 443:443
    restart: always
    networks: 
      - nginx
  resume:
    container_name: resume
    image: harbor.chlin.tk/vue/resume:ccb87bb-20210506-0214
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=3000
    ports:
      - 3000:3000
    restart: always
    networks: 
      - nginx
  linebot-linux:
    container_name: linebot-linux
    image: harbor.chlin.tk/python/linebot-linux:8317dba-20210508-1846
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/volumes/linebot-linux:/usr/src/app/logs
    ports:
      - 3001:3001
    restart: always
    networks: 
      - nginx
  wedding:
    container_name: wedding
    image: harbor.chlin.tk/vue/wedding:8548fb0_20210407120454
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 8050:8050
    restart: always
    networks: 
      - nginx
  university:
    image: harbor.chlin.tk/python/university:d5f93b7-20210401-0054
    container_name: university
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/volumes/university:/usr/src/app/logs
      - ~/volumes/university/upload:/usr/src/app/university/upload
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    ports: 
      - 8336:8336
    environment:
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=8336
      - LOG_LEVEL=INFO
      - LOG_FOLDER_PATH=logs/
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_ACCOUNT='root'
      - DB_PASSWORD='password'
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8336/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s
    restart: always
    networks: 
      - nginx
  vote:
    image: harbor.chlin.tk/python/vote:8d8530f-20210310-1843 
    container_name: vote
    environment:
      - TZ=Asia/Taipei
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=8333
      - LOG_LEVEL=INFO
      - START_TIME=23
      - END_TIME=0
      - CALL_DIRECTION=outbound
      - LOG_FOLDER_PATH=logs/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/volumes/vote:/usr/src/app/logs
    ports: 
      - 8333:8333
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8333/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s
    restart: always
    networks: 
      - nginx
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ~/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: deployer
      MYSQL_PASSWORD: password
    ports:
      - "172.17.0.1:3306:3306"
    networks:
      - nginx
networks:
  nginx:
    external: true
    name: nginx
