version: "3.7"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: harbor.chlin.tk/nginx/reverse-proxy:${TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf.d:/etc/nginx/conf.d/
    ports:
      - 8888:80
    network_mode: "host"
    restart: always
    networks: 
      - emotibot
networks:
  emotibot:
    external: true
    name: emotibot
