version: "3.7"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: harbor.chlin.tk/nginx/reverse-proxy:${TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf.d:/etc/nginx/conf.d/
    environment:
      BF_IP: http://192.168.3.216
    ports:
      - target: 8336
        published: 8336
        protocol: tcp
        mode: host
    # network_mode: "host"
    restart: always
