version: "3.7"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: harbor.chlin.tk/nginx/reverse-proxy:${TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf.d:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./cert/harbor_cert:/etc/cert
      - ./cert/product:/etc/letsencrypt/product
    ports:
      - 80:80
      - 443:443
    restart: always
    networks: 
      - nginx
  resume:
    container_name: resume
    image: harbor.chlin.tk/vue/resume:latest
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=3000
    ports:
      - 3000:3000
    restart: always
    networks: 
      - nginx
  linebot:
    container_name: linebot
    image: harbor.chlin.tk/python/linebot:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/volumes/linebot:/usr/src/app/logs
    ports:
      - 3001:3001
    restart: always
    networks: 
      - nginx
    environment:
      - TZ=Asia/Taipei
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=3001
      - SERVER_IP=127.0.0.1
      - LOG_LEVEL=INFO
      - LOG_FOLDER_PATH=logs/
      - DOCKER_NETWORK='alpine-net'
      - RESUME_HEALTH_API='https://resume-chlin.herokuapp.com/healthckeck'
      - AVALON_HEALTH_API='https://avalon-chlin.herokuapp.com/healthcheck'
      - CHANNEL_SECRET='ba59b9bc9e8805a7972fdd6cb1566a03'
      - CHANNEL_TOKEN='EnSpzk7sQ04AnBwO34YukvfIRF33MeJzwlHuuwH8eCT9rUXLO6wr0fu50TNllOLh+YkK0I8Vjxx2gVllw5Im82OeAvPTc40wS7HLHS6NdcQUazxxS9myCePXHsITe2kqhCCCWHf0o57+HUo364lvqQdB04t89/1O/w1cDnyilFU='
      - CHROMEDRIVER_PATH='http://127.0.0.1:4444/wd/hub'
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_ACCOUNT=root
      - DB_PASSWORD=password
      - REDIS_IP=172.17.0.1
      - REDIS_PORT=6379
  websocket:
    image: harbor.chlin.tk/java/websocket:dcf258b-20210531-0533
    container_name: websocket
    environment:
      - TZ=Asia/Taipei
    volumes:
      # - ~/volumes/websocket:/usr/src/app/logs
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 3002:8080
    restart: always
    networks: 
      - nginx
  websocket-ui:
    image: harbor.chlin.tk/vue/websocket-ui:latest
    container_name: websocket-ui
    ports: 
      - 3003:3003
    restart: always
    networks: 
      - nginx
  avalon:
    image: harbor.chlin.tk/vue/avalon:latest 
    container_name: avalon
    restart: always
    environment:
      - PORT=3004
    ports: 
      - "3004:3004"
    networks: 
      - nginx
  wedding:
    container_name: wedding
    image: harbor.chlin.tk/vue/wedding:8548fb0_20210407120454
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 8050:8050
    restart: always
    networks: 
      - nginx
  university-demo:
    image: harbor.chlin.tk/python/university-demo:latest
    container_name: university-demo
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/volumes/university:/usr/src/app/logs
      - ~/volumes/university/upload:/usr/src/app/university/upload
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    ports: 
      - 3012:3012
    environment:
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=3012
      - LOG_LEVEL=INFO
      - LOG_FOLDER_PATH=logs/
      - DB_HOST=172.17.0.1
      - DB_PORT=3307
      - DB_ACCOUNT='root'
      - DB_PASSWORD='123456'
    restart: always
    networks: 
      - nginx
  university:
    image: harbor.chlin.tk/python/university:d5f93b7-20210401-0054
    container_name: university
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/volumes/university:/usr/src/app/logs
      - ~/volumes/university/upload:/usr/src/app/university/upload
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    ports: 
      - 8336:8336
    environment:
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=8336
      - LOG_LEVEL=INFO
      - LOG_FOLDER_PATH=logs/
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_ACCOUNT='root'
      - DB_PASSWORD='password'
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8336/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s
    restart: always
    networks: 
      - nginx
  fb:
    image: harbor.chlin.tk/python/fb:fb-test
    container_name: fb
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/volumes/fb:/usr/src/app/logs
    ports: 
      - 3010:3010
    env_file:
      - easycard.env
    environment:
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=3010
      - LOG_LEVEL=INFO
      - LOG_FOLDER_PATH=logs/
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_ACCOUNT='root'
      - DB_PASSWORD='password'
    restart: always
    networks: 
      - nginx
  fbt:
    image: harbor.chlin.tk/python/fb:latest
    container_name: fbt
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/volumes/fbt:/usr/src/app/logs
    ports: 
      - 3011:3011
    environment:
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=3011
      - LOG_LEVEL=INFO
      - LOG_FOLDER_PATH=logs/
      - WELCOME_MESSAGE='{"data":"感謝與我們聯繫~\n本平台不提供對話服務，如有問題可點選下方選項。"}'
      - MESSAGE_WELCOME='true'
      - GET_START_WELCOME='false'
      - VERIFY_TOKEN='123456'
      - ACCESS_TOKEN='{"105566678410846":"EAAk4H5wUh88BAOpXY9vN56Sc11hFtNCZCVyWQkvijsDzcPaUZCuZCKYCrbfVZCUZCS4PfEZArJLhNHUrUf0ZCUulB5DnABqzBVdkVVGEosfNcV5lAlD6tmLdkZC273Ihd06qHQSO30vPV0AWdZCuyz8cqgqGrtiQSyrGhOEr8ytdCjmWbD6IjJFc5","100903557951068":"EAAGJwZCK6hFUBANZCXTgn9pc6YnvBZBwKFGYHUjVEop2ZBT1CDBpg40G6WDyt8nIjiUe2nKZCr3fZBVAi29QoDL6SeZCDtOoGQXjb4hoTsf0sp1MZCZBOWjXVw420V7QSEUGFlF2ZCTFIvVD3aeapAkiSCmnz7HJGRHLuLMSwrIiTmS90RgCqSSi4V","108433087175265":"EAAFNM3mDiKcBAI1S8R6rIZAKZCiUZC33RDkfWpJvdpwHoT6uZC5uGdhjjeGDCFklGra44ZA9JccSAdZAp0TAG9KexcjEii3Mb7ZCt8n9zUwLwkibAjgbIt0N0nSPFaVYWGRrPs619xhO7sxRFUCdBLZCtzfv1p0cTxgR01EPmYO9BSmEZA7hTQhHg","107881503944278":"EAAFNM3mDiKcBANqDgl2xfqpTQCqNjqkcZAWtDHaUkMCmaBcPy8RMAK4GwnmTvtarTsRZArWMaNcBjpJnu0HbOnZAZBi6JJvTSyvfaJsEHHOrCmE5wDKEZAmADLWtmDwDB0u19EDeeNkjjmkmsUZAGMmKrj1NG8z1IhFZBrbXZBstRmWZBXNKbfMMe","106728057354969":"EAAFNM3mDiKcBAHtM9hRjlS1R6KL3vuYfwv2dlvZBE27wlLZA8j9vkv0L9lk4ZADMwE6dK05XCdZB0p8Tdj7FsG7FjbG9AUTnw9YdaPCOP8UNPhkEp7XmYAmKWw9z8FSO0gu2y6cjs3t3iAzgxbdoUdyY4ZCJkcXBmn4hrt0AEl1NwGocFsrUn"}'
      - PAYLOAD='[{"attachment":{"type":"template","payload":{"template_type":"generic","elements":[{"title":"快速服務","image_url":"https://i.postimg.cc/bNPpTY4v/fbbanner01-906x600.png","subtitle":"請左右滑動卡片以完整呈現選單","default_action":{"type":"web_url","url":"https://www.easycard.com.tw","webview_height_ratio":"tall"},"buttons":[{"type":"web_url","url":"https://ezweb.easycard.com.tw/eccl2/apply!reportloss.action","title":"我要掛失"},{"type":"web_url","url":"https://www.easycard.com.tw/introduction?id=3","title":"退卡方式說明"},{"type":"web_url","url":"https://shop.easycard.com.tw/ttWeb/search.aspx","title":"退費進度查詢"}]},{"title":"快速服務","image_url":"https://i.postimg.cc/MH7xSgfx/fbbanner02-906x600.png","subtitle":"請左右滑動卡片以完整呈現選單","default_action":{"type":"web_url","url":"https://www.easycard.com.tw/","webview_height_ratio":"tall"},"buttons":[{"type":"web_url","url":"https://ezweb.easycard.com.tw/search/CardSearch.php","title":"悠遊卡交易紀錄"},{"type":"web_url","url":"https://ezweb.easycard.com.tw/eccl2/apply!Inquire.action","title":"票卡效期查詢"},{"type":"web_url","url":"https://ezweb.easycard.com.tw/eccl2/apply.action","title":"記名申請"}]}]}}},{"attachment":{"type":"template","payload":{"template_type":"button","text":"也可以找客服小幫手協助您~","buttons":[{"type":"web_url","url":"https://chatbot.easycard.com.tw/chatbot/#/robotchat?platform=FB","title":"小幫手嗶寶"}]}}},{"text":"或撥悠遊卡客服專線\n412-8880\n(手機及金馬地區請加02)"}]'
    restart: always
    networks: 
      - nginx
  btc:
    image: harbor.chlin.tk/python/btc:latest
    container_name: btc
    environment:
      - TZ=Asia/Taipei
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=3007
      - LOG_LEVEL=INFO
      - LOG_FOLDER_PATH=logs/
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_ACCOUNT='root'
      - DB_PASSWORD='password'
    volumes:
      - ~/volumes/btc:/usr/src/app/logs
      - ~/etc/timezone:/etc/localtime:ro
    ports:
      - 3007:3007
  vote:
    image: harbor.chlin.tk/python/vote:8d8530f-20210310-1843 
    container_name: vote
    environment:
      - TZ=Asia/Taipei
      - IS_LOADED=LOAD_ENV_FILE_SUCCESS
      - PORT=8333
      - LOG_LEVEL=INFO
      - START_TIME=23
      - END_TIME=0
      - CALL_DIRECTION=outbound
      - LOG_FOLDER_PATH=logs/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/volumes/vote:/usr/src/app/logs
    ports: 
      - 8333:8333
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8333/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s
    restart: always
    networks: 
      - nginx
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ~/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: deployer
      MYSQL_PASSWORD: password
    ports:
      - "172.17.0.1:3306:3306"
    networks:
      - nginx
  redis:
    restart: always
    container_name: redis-linch
    image: redis:5.0.5-alpine 
    ports:
      - "172.17.0.1:6379:6379"
    volumes:
      - ~/volumes/redis-data:/data
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx
